#pragma once

#include <uv.h>

#define UVPP_UV_VERSION_AT_LEAST(major, minor, patch) \
  (UV_VERSION_HEX >= (((major) << 16) | ((minor) << 8) | (patch)))

#define UVPP_HAS_TCP_INIT_EX UVPP_UV_VERSION_AT_LEAST(1, 7, 0)
#define UVPP_HAS_TCP_CLOSE_RESET UVPP_UV_VERSION_AT_LEAST(1, 32, 0)
#define UVPP_HAS_TCP_REUSEPORT UVPP_UV_VERSION_AT_LEAST(1, 49, 0)

#define UVPP_HAS_UDP_INIT_EX UVPP_UV_VERSION_AT_LEAST(1, 7, 0)
#define UVPP_HAS_UDP_CONNECT UVPP_UV_VERSION_AT_LEAST(1, 27, 0)
#define UVPP_HAS_UDP_SOURCE_MEMBERSHIP UVPP_UV_VERSION_AT_LEAST(1, 32, 0)
#define UVPP_HAS_UDP_MMSG_CHUNK UVPP_UV_VERSION_AT_LEAST(1, 35, 0)
#define UVPP_HAS_UDP_RECVMMSG_FLAG UVPP_UV_VERSION_AT_LEAST(1, 37, 0)
#define UVPP_HAS_UDP_USING_RECVMMSG UVPP_UV_VERSION_AT_LEAST(1, 39, 0)
#define UVPP_HAS_UDP_MMSG_FREE UVPP_UV_VERSION_AT_LEAST(1, 40, 0)
#define UVPP_HAS_UDP_LINUX_RECVERR UVPP_UV_VERSION_AT_LEAST(1, 42, 0)
#define UVPP_HAS_UDP_REUSEPORT UVPP_UV_VERSION_AT_LEAST(1, 49, 0)
#define UVPP_HAS_UDP_TRY_SEND2 UVPP_UV_VERSION_AT_LEAST(1, 50, 0)
