#pragma once

#include <uv.h>

#define UVPP_UV_VERSION_AT_LEAST(major, minor, patch) \
  (UV_VERSION_HEX >= (((major) << 16) | ((minor) << 8) | (patch)))

#define UVPP_HAS_TCP_INIT_EX UVPP_UV_VERSION_AT_LEAST(1, 7, 0)
#define UVPP_HAS_TCP_CLOSE_RESET UVPP_UV_VERSION_AT_LEAST(1, 32, 0)
#define UVPP_HAS_TCP_REUSEPORT UVPP_UV_VERSION_AT_LEAST(1, 49, 0)

#define UVPP_HAS_TIMER_GET_DUE_IN UVPP_UV_VERSION_AT_LEAST(1, 40, 0)

#define UVPP_HAS_TTY_VTERM_STATE UVPP_UV_VERSION_AT_LEAST(1, 33, 0)

#define UVPP_HAS_PIPE_BIND2 UVPP_UV_VERSION_AT_LEAST(1, 46, 0)
#define UVPP_HAS_PIPE_CONNECT2 UVPP_UV_VERSION_AT_LEAST(1, 46, 0)

#define UVPP_HAS_PROCESS_GET_PID UVPP_UV_VERSION_AT_LEAST(1, 19, 0)
#define UVPP_HAS_PROCESS_WINDOWS_HIDE_CONSOLE_GUI UVPP_UV_VERSION_AT_LEAST(1, 24, 0)
#define UVPP_HAS_PROCESS_WINDOWS_FILE_PATH_EXACT_NAME UVPP_UV_VERSION_AT_LEAST(1, 48, 0)

#define UVPP_HAS_OS_HOMEDIR UVPP_UV_VERSION_AT_LEAST(1, 6, 0)
#define UVPP_HAS_OS_TMPDIR UVPP_UV_VERSION_AT_LEAST(1, 9, 0)
#define UVPP_HAS_OS_ENVIRONMENT UVPP_UV_VERSION_AT_LEAST(1, 12, 0)
#define UVPP_HAS_OS_GETHOSTNAME UVPP_UV_VERSION_AT_LEAST(1, 12, 0)
#define UVPP_HAS_OS_GETPPID UVPP_UV_VERSION_AT_LEAST(1, 16, 0)
#define UVPP_HAS_OS_GETPID UVPP_UV_VERSION_AT_LEAST(1, 18, 0)
#define UVPP_HAS_OS_PRIORITY UVPP_UV_VERSION_AT_LEAST(1, 23, 0)
#define UVPP_HAS_OS_UNAME UVPP_UV_VERSION_AT_LEAST(1, 25, 0)
#define UVPP_HAS_SLEEP UVPP_UV_VERSION_AT_LEAST(1, 34, 0)
#define UVPP_HAS_AVAILABLE_PARALLELISM UVPP_UV_VERSION_AT_LEAST(1, 44, 0)

#define UVPP_HAS_THREAD_DETACH UVPP_UV_VERSION_AT_LEAST(1, 50, 0)

#define UVPP_HAS_FS_STATFS UVPP_UV_VERSION_AT_LEAST(1, 31, 0)
#define UVPP_HAS_FS_MKSTEMP UVPP_UV_VERSION_AT_LEAST(1, 34, 0)

#define UVPP_HAS_UDP_INIT_EX UVPP_UV_VERSION_AT_LEAST(1, 7, 0)
#define UVPP_HAS_UDP_CONNECT UVPP_UV_VERSION_AT_LEAST(1, 27, 0)
#define UVPP_HAS_UDP_SOURCE_MEMBERSHIP UVPP_UV_VERSION_AT_LEAST(1, 32, 0)
#define UVPP_HAS_UDP_MMSG_CHUNK UVPP_UV_VERSION_AT_LEAST(1, 35, 0)
#define UVPP_HAS_UDP_RECVMMSG_FLAG UVPP_UV_VERSION_AT_LEAST(1, 37, 0)
#define UVPP_HAS_UDP_USING_RECVMMSG UVPP_UV_VERSION_AT_LEAST(1, 39, 0)
#define UVPP_HAS_UDP_MMSG_FREE UVPP_UV_VERSION_AT_LEAST(1, 40, 0)
#define UVPP_HAS_UDP_LINUX_RECVERR UVPP_UV_VERSION_AT_LEAST(1, 42, 0)
#define UVPP_HAS_UDP_REUSEPORT UVPP_UV_VERSION_AT_LEAST(1, 49, 0)
#define UVPP_HAS_UDP_TRY_SEND2 UVPP_UV_VERSION_AT_LEAST(1, 50, 0)

#define UVPP_HAS_IF_INDEX_TO_NAME UVPP_UV_VERSION_AT_LEAST(1, 16, 0)
#define UVPP_HAS_IF_INDEX_TO_IID UVPP_UV_VERSION_AT_LEAST(1, 16, 0)

#define UVPP_HAS_RANDOM UVPP_UV_VERSION_AT_LEAST(1, 33, 0)
