name: C/C++ CI

on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt install -y clang libuv1-dev libgtest-dev libfmt-dev
    - name: Install SonarCloud Cpp build-wrapper
      run: |
        wget http://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        unzip build-wrapper-linux-x86.zip
    - name: Make binary and execute tests
      run: ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory make build
#    - name: Display log content for analyse
#      run: cat build_wrapper_output_directory/*.log
#    - name: Display JSON content for analyse
#      run: cat build_wrapper_output_directory/*.json
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=peio42-github
          -Dsonar.projectKey=org.blutch:uvpp
          -Dsonar.sources=.
          -Dsonar.cfamily.build-wrapper-output=build_wrapper_output_directory

#          -Dsonar.sources=uvpp
#          -Dsonar.tests=test