name: C/C++ CI

on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt install -y clang libuv1-dev libgtest-dev libfmt-dev
    - name: Which directory
      run: pwd
    - name: Install SonarCloud Cpp build-wrapper
      run: |
        wget http://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        unzip build-wrapper-linux-x86.zip
    - name: Make binary and execute tests
      run: ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw_out make build
    - name: Hack Sonar JSON file with path in docker container
      run: sed -i 's?/home/runner/work/uvpp/uvpp?/github/workspace?g' bw_out/build-wrapper-dump.json
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=peio42-github
          -Dsonar.projectKey=org.blutch:uvpp
          -Dsonar.sources=uvpp,test
          -Dsonar.cfamily.build-wrapper-output=bw_out
          -Dsonar.verbose=true
