name: C/C++ CI

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt install -y clang libuv1-dev libgtest-dev libfmt-dev
    - name: Make binary and execute tests
      run: make
