name: C/C++ CI

on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt install -y clang libuv1-dev libgtest-dev libfmt-dev
    - name: Which directory
      run: pwd
    - name: Install SonarCloud scanner
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216-linux.zip
        unzip sonar-scanner-cli-4.5.0.2216-linux.zip
    - name: Install SonarCloud Cpp build-wrapper
      run: |
        wget http://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        unzip build-wrapper-linux-x86.zip
    - name: Make binary and execute tests
      run: ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw_out make build
    - name: SonarCloud Scan
      run: ./sonar-scanner-4.5.0.2216-linux/bin/sonar-scanner \
        -Dsonar.organization=peio42-github \
        -Dsonar.projectKey=org.blutch:uvpp \
        -Dsonar.sources=uvpp,test \
        -Dsonar.cfamily.build-wrapper-output=bw_out
